image: node:14
variables:
    IMAGE_NAME: baopham2002/simple_calculator
    IMAGE_TAG: node-app-1.0
stages:
  - test
  - build

run_tests:
  stage: test
  script:
    - npm install
    - npm test

build-image:
  stage: build
  image: docker:27.0.3-cli
  services:
    - docker:27.0.3-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

    